replicaCount: 1

image:
  repository: 713881828888.dkr.ecr.us-east-1.amazonaws.com/mlops
  tag: "latest"
  pullPolicy: Always

containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: false
