replicaCount: 1

image:
  repository: 713881828888.dkr.ecr.us-east-1.amazonaws.com/mlops
  tag: "latest"
  pullPolicy: Always

containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  hosts: mlops.habibur-rahman.com
  tls:
    enabled: true
    host: habibur-rahman.com
