replicaCount: 1

image:
  repository: 590184076390.dkr.ecr.eu-west-2.amazonaws.com/ai-model
  tag: "latest"
  pullPolicy: Always

containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  hosts: ai.labs.mustafamirreh.com
  tls:
    enabled: true
    host: labs.mustafamirreh.com
